server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能,利用微服务名进行路由
      routes:
        - id: payment_routh # 路由ID,没有固定规则但要求唯一
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 动态匹配提供服务的路由地址,格式是lb:// 加上服务名称
          predicates:
            - Path=/pay/payment/get/**  # 断言,路径相匹配的进行路由,如果有上下文，要加上上下文

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service # 动态匹配提供服务的路由地址
          predicates:
            - Path=/pay/payment/lb/**

        - id: payment_routh3  # 模拟config中的配置,更加直白,访问localhost:9527/finance会转发到http://news.baidu.com/finance
          uri: http://news.baidu.com
          predicates:
            - Path=/finance

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true # 将自己注册进Eureka Server,默认是true
    fetch-registry: true  # 从Eureka Server拉取已有的注册信息，默认是true
    service-url:
       defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 注册到Eureka集群
