server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

# eureka client配置
eureka:
  client:
    register-with-eureka: true # 将自己注册进Eureka Server,默认是true
    fetch-registry: true  # 从Eureka Server拉取已有的注册信息，默认是true
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 注册到Eureka集群
#  instance:
#    instance-id: order80 # Eureka client 名称
#    prefer-ip-address: true # 访问路径可以显示IP地址

# 设置feign客户端超时时间,默认支持ribbon，1秒超时
# 第一种：通过ribbon
ribbon:
  ReadTimeout: 5000 # 建立连接所用时间
  ConnectTimeout: 5000 # 建立连接后从服务器读取到可用资源所用的时间
# 第二种：通过feign设置
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
logging:
  level:
    # 设置feign日志监控的接口
    com.stephen.springcloud.service.PaymentFeignService: debug
